apps/beltreviewer_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^register$', views.register),
    url(r'^login$', views.login),
]

apps/books_app/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
    url(r'^books$', views.index),
    url(r'^addPage$', views.addPage),
    url(r'^addBook$', views.addBook),
    url(r'^addReview$', views.addReview),
    url(r'^review$', views.review),
]

beltreviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.beltreviewer_app.urls')),
    url(r'^', include('apps.books_app.urls')),
]

apps/beltreviewer_app/models.py
from __future__ import unicode_literals

from django.db import models

import re

import bcrypt

# Create your models here.

class UserManager(models.Manager):
    def registerVal(self, postData):
        results = {'status':True, 'errors':[]}
        if not postData['first_name'] or len(postData['first_name']) < 2:
            results['status']=False
            results['errors'].append("First Name must be more than one character.")
        if not postData['last_name'] or len(postData['last_name']) < 2:
            results['status']=False
            results['errors'].append("Last Name must be more than one character.")
        if not postData['email'] or not re.match(r"(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)", postData['email']):
            results['status']=False
            results['errors'].append("Email address is not valid.")
        if not postData['password'] or len(postData['password']) < 8 or postData['password'] != postData['confirmpw']:
            results['status']=False
            results['errors'].append("Password must be at least 8 characters, and both password fields must match.")
        if results['status']==True:
            user = User.objects.filter(email=postData['email'].lower())
            if len(user)!=0:
                results['status']=False
                results['errors'].append('Registration failed. Please try again.')
                return results
            else:
                hashedpw = bcrypt.hashpw(postData['password'].encode(), bcrypt.gensalt())
                User.objects.create(first_name=postData['first_name'], last_name=postData['last_name'], email=postData['email'].lower(), password=hashedpw)
                results['errors'].append("Registration successful. Please log in.")
                return results
        return results

    def loginVal(self, postData):
        results = {'status':True, 'errors':[], 'user':{}, 'id':""}
        if not postData['email'] or not postData['password']:
            results['status']=False
            results['errors'].append("Login failed. Please try again.")
            return results
        else:
            user = User.objects.filter(email=postData['email'].lower())
            print user
            if bcrypt.hashpw(postData['password'].encode(), user[0].password.encode()) != user[0].password:
                results['status']=False
                results['errors'].append("Login failed. Please try again.")
                return results
            else:
                results['user']=user
                results['id']=user[0].id             
                return results



class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    objects = UserManager()

apps/books_app/models.py
from __future__ import unicode_literals

from django.db import models
from ..beltreviewer_app.models import User

# Create your models here.
class BookManager(models.Manager):
    def display(self):
        books = Book.objects.all()
        return books


class AuthorManager(models.Manager):
    def addNew(self, postData):
        results = {'errors':[], 'status':True}
        if postData['author']:
            author = Author.objects.filter(name=postData['author'])
            if len(author)!=0:
                results['errors'].append("That author is already in the system. Please choose from the drop down list.")
                results['status']=False
                return results
            else:
                Author.objects.create(name=postData['author'])
                author = Author.objects.get(name=postData['author'])
                Book.objects.create(title=postData['title'], author=author)
                book = Book.objects.get(title=postData['title'])
                Review.objects.create(content=postData['review'], book = book)
                return results

class ReviewManager(models.Manager):
    def test(self):
        return self

class Author(models.Model):
    name = models.CharField(max_length=100)
    objects = AuthorManager()

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BookManager()

class Review(models.Model):
    content = models.TextField()
    book = models.ForeignKey(Book)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ReviewManager()

apps/beltreviewer_app/views.py
from django.shortcuts import render, redirect

from .models import User

from django.contrib import messages

# Create your views here.
def index(request):
    return render(request, 'beltreviewer_app/index.html')

def register(request):
    results = User.objects.registerVal(request.POST)
    for error in results['errors']:
        messages.error(request, error)
    return redirect('/')

def login(request):
    results = User.objects.loginVal(request.POST)
    if results['status']==False:
        for error in results['errors']:
            messages.error(request, error)
        return redirect('/')
    else:
        request.session['first_name']=User.objects.get(id=results['id']).first_name
        print request.session['first_name']
        return redirect('/books')

apps/books_app/views.py
from django.shortcuts import render, redirect

from .models import Book, User, Author, Review
from django.contrib import messages


# Create your views here.
def index(request):
    books = Book.objects.display()
    reviews = Review.objects.all()
    context = {'books':books, 'reviews':reviews}
    return render(request, 'books_app/index.html', context)

def addPage(request):
    authors = Author.objects.all()
    context = {'authors':authors}
    return render(request, 'books_app/addPage.html', context)


def addBook(request):
    results = Author.objects.addNew(request.POST)
    if results['status']==False:
        for error in results['errors']:
            messages.error(request, error)
        return redirect('/addPage')
    else:
        return redirect('/books')

def addReview(request):
    book = Book.objects.get(id=request.POST['bookname'])
    context = {
        'bookTitle':book.title,
        'id': book.id,
        'author': book.author,
    }
    return render(request, 'books_app/addReview.html', context)

apps/beltreviewer_app/templates/beltreviewer_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Welcome!</h1>
    {% if messages %}
        {% for message in messages %}
            <p>{{message}}</p>
        {% endfor %}
    {% endif %}

    <h3>Register</h3>
    <form action='/register' method="POST">
        {% csrf_token %}
        First Name: <input type='text' name='first_name' placeholder="Enter your first name"><br>
        <br>
        Last Name: <input type='text' name='last_name' placeholder="Enter your last name"><br>
        <br>
        Email Address: <input type='text' name='email' placeholder="Enter your email address"><br>
        <br>
        Password: <input type='text' name='password' placeholder="Create a Password"><br>
        <br>
        Confirm Password: <input type='text' name='confirmpw' placeholder="Re-type your Password"><br>
        <br>
        <input type='submit' value="REGISTER">   
    </form>

    <h3>Login</h3>
    <form action='/login' method="POST">
        {% csrf_token %}
        Email Address: <input type='text' name='email' placeholder="Enter your email address"><br>
        <br>
        Password: <input type='text' name='password' placeholder="Create a Password"><br>
        <br>
        <input type='submit' value="LOGIN">   
    </form>
</body>
</html>

apps/beltreviewer_app/templates/beltreviewer_app/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Success Page</h1>
</body>
</html>

apps/books_app/templates/books_app/addPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Add a Book...</h1>
    {% if messages %}
        {% for message in messages %}
            {{message}}
        {% endfor %}
    {% endif %}

    <form action='addBook' method="POST">
        {% csrf_token %}
        Title: <input type='text' name='title' placeholder="Book Title"><br>
        Choose an author from the list or add a new author below:
        <select> 
            {% for author in authors %}
                <option value={{author}}>{{author.name}}</option>
            {% endfor %}
        </select><br>
        Add a new author: <input type='text' name='author' placeholder="Author's Name"><br>
        Review: <textarea rows=8 cols=40 name='review'></textarea><br>
        Rating: <select>
            <option value='1'>1</option>
            <option value='2'>2</option>
            <option value='3'>3</option>
            <option value='4'>4</option>
            <option value='5'>5</option>
        </select><br>
        <input type='submit' value="Add!">

    </form>
</body>
</html>

apps/books_app/templates/books_app/addReview.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Add a review for {{bookTitle}}, by {{author.name}}</h1>
    <form action='review' method="POST">
        {% csrf_token %}
        <textarea name='review' rows=10 cols=50 placeholder="Write review here..."></textarea><br>
        <input type='hidden' name='id' value='{{id}}'>
        <input type='submit' value='Post Review'>
    </form>
</body>
</html>

apps/books_app/templates/books_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Books!</h1>
    <h3>Welcome {{request.session.first_name}}!</h3>
    {% for book in books %}
        <div style="border: 2px solid black">
        <p>{{book.title}}, by {{book.author.name}}</p>
            {% for something in book.review_set.all %}
                {{something.content}}
            {% endfor %}
            <form action='/addReview' method="POST">
                {% csrf_token %}
                <input type="hidden" name='bookname' value='{{book.id}}'>
                <input type='submit' value='POST REVIEW'>
                
            </form>
        </div><br>
        
    {% endfor %}

    <form action='/addPage' method='POST'>
        {% csrf_token %}
        <input type='submit' value='Add a Book'>
    </form>
</body>
</html>